apiVersion: v1
kind: Service
metadata:
  name: upload-service
  labels:
    app: upload-service
spec:
  type: ClusterIP
  selector:
    app: upload-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
