apiVersion: v1
kind: Service
metadata:
  name: upload-service
  labels:
    app: upload-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: upload-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
